#
# dbt-core develop environments
# dind しようと思ったけど特に意味なかった
#

FROM docker:latest

#
# Install Pyhton(Version 指定は無いから version 3 最新で、、、)
#
RUN apk update && apk upgrade && \
    apk --update-cache add \
        bash \
        make \
        libcaca-apps \
        git \
        python3 \
        python3-dev \
        py3-pip \
        pytest \
        postgresql && \
    pip install --upgrade pip && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
