#
# dbt-core develop environments
# (Python 3.12 だと DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated 言われるので 3.11で、、、)
#
FROM python:3.11.7

#
# Install 
#
RUN apt update && \
    apt install --no-install-recommends -y \
        bash \
        make \
        caca-utils \
        git \
        postgresql && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip install --upgrade pip

